name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: cd src && zip -r '../HKUST Timetable Planner Stylus.zip' . && cd ..
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: HKUST Timetable Planner Stylus.zip